# Generated by Django 3.2.9 on 2021-12-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='deliver_date',
            field=models.DateField(auto_now=True),
        ),
    ]
