# Generated by Django 3.2.9 on 2021-12-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_alter_date_deliver_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='deliver_date',
            field=models.DateField(),
        ),
    ]
